#!/usr/bin/python

import os

def setup_link(svn, ws, dev, is_comp):
    src="%s/src/%s/%s" % (svn, ("devices","components")[is_comp], dev)
    dst="%s/modules" % ws
    cmd="ln -s %s %s" % (src, dst)
    os.system(cmd)
    print "cmd: %s" % cmd


if __name__ == "__main__":
    svn="/space/work/simics/ivho/4.4_lsi_acp34xx"
    ws="/space/work/simics/nca/workspace"
    f=open("acp3400.devices")
    while True:
        x=f.readline().rstrip('\n').split(' ')
        print x
        if len(x) != 2:
            break
        setup_link(svn, ws, x[1], x[0]=="C")
#    setup_link("", "/space/work/simics/nca/workspace", "ACP3400-devices", False)

